### ISSUE TITLE
InstaRecon on Infoooze refturns error

### ISSUE THREAD

**Issue by Cistonne** [7ORP3DO/infoooze#2]
### Describe the bug
Great looking and useful app BTW .  

When I run InstaRecon, after entering a Username, an error is returned with the following information:
Thank you.
Cistonne

### Screenshots

usr/local/lib/node_modules/infoooze/src/instaRecon.js:31
        let IGData = response.body.graphql.user;
                                           ^

TypeError: Cannot read properties of undefined (reading 'user')
    at Request._callback (/usr/local/lib/node_modules/infoooze/src/instaRecon.js:31:44)
    at Request.self.callback (/usr/local/lib/node_modules/infoooze/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/infoooze/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/infoooze/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v17.7.2

### System Information

**Infoooze Version** : 1.0.2
**Node Version** : v17.7.2
**OS Type** : Linux Ubuntu 20.04 LTS
**OS Version** : 5.13.0-35-generic
**OS Plateform** : linux

**Comment by 7ORP3DO** [comment]
Hii @Cistonne ,

It looks like your IP has been temporarily blocked by Instagram.  Usually this happens if you search fast or use a VPN.  If your IP is also temporarily blocked then you can easily get a new IP by resetting the modem or switching networks.  However, after some time your old IP will also be unblocked.

_Please let me know if it works or not._
